export const ROLES = { ADMIN: 'ADMIN', TEACHER: 'TEACHER', STUDENT: 'STUDENT' };

export const EXAM_TYPES = {
  PRACTICE: 'PRACTICE',
  SELF_TEST: 'SELF_TEST',
  ASSESSMENT: 'ASSESSMENT',
  WCL: 'WCL',
  ACL: 'ACL',
};

export const SPLITUP_CATEGORY = {
  ADDITION_AND_SUBTRACTION: 'ADDITION_AND_SUBTRACTION',
  MULTIPLICATION: 'MULTIPLICATION',
  DIVISION: 'DIVISION',
};

export const MATH_TYPE = {
  ADDITION: 'ADDITION',
  SUBTRACTION: 'SUBTRACTION',
  ADDITION_AND_SUBTRACTION: 'ADDITION_AND_SUBTRACTION',
  MULTIPLICATION: 'MULTIPLICATION',
  DIVISION: 'DIVISION',
};

export const NOTIFICATION_AUDIENCES = {
  ALL: 'ALL',
  STUDENTS: 'STUDENTS',
  TEACHERS: 'TEACHERS',
};

export const NOTIFICATION_TYPES = {
  BATCH_JOIN_NOTIFICATION: 'BATCH_JOIN_NOTIFICATION',
  EXAM_NOTIFICATION: 'EXAM_NOTIFICATION',
  INFORMATIONAL_NOTIFICATION: 'INFORMATIONAL_NOTIFICATION',
};

export const BATCH_REQUEST_TYPE = {
  JOIN: 'JOIN',
  INVITE: 'INVITE',
};

export const BATCH_REQUEST_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
};
